import { Injectable } from '@angular/core';
import { Category, Product, ProductReview, Banner, Coupon, Order, Customer, Vendor, Admin, ReturnRequest, SupportTicket } from '../models';

@Injectable({ providedIn: 'root' })
export class DataService {
  private categories: Category[] = [
    { id: 'cat1', name: 'Electronics', slug: 'electronics', description: 'Latest electronic gadgets and devices', image: 'https://images.pexels.com/photos/3945683/pexels-photo-3945683.jpeg?auto=compress&cs=tinysrgb&w=400', icon: 'devices', parentId: undefined, productCount: 1250, isActive: true },
    { id: 'cat2', name: 'Fashion', slug: 'fashion', description: 'Trendy clothing and accessories', image: 'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=400', icon: 'checkroom', parentId: undefined, productCount: 3420, isActive: true },
    { id: 'cat3', name: 'Home & Kitchen', slug: 'home-kitchen', description: 'Everything for your home', image: 'https://images.pexels.com/photos/1643343/pexels-photo-1643343.jpeg?auto=compress&cs=tinysrgb&w=400', icon: 'home', parentId: undefined, productCount: 890, isActive: true },
    { id: 'cat4', name: 'Sports & Fitness', slug: 'sports-fitness', description: 'Sports equipment and fitness gear', image: 'https://images.pexels.com/photos/4162472/pexels-photo-4162472.jpeg?auto=compress&cs=tinysrgb&w=400', icon: 'sports_soccer', parentId: undefined, productCount: 567, isActive: true },
    { id: 'cat5', name: 'Books', slug: 'books', description: 'Books across all genres', image: 'https://images.pexels.com/photos/159711/books-bookstore-book-reading-159711.jpeg?auto=compress&cs=tinysrgb&w=400', icon: 'menu_book', parentId: undefined, productCount: 2340, isActive: true },
    { id: 'cat6', name: 'Beauty & Personal Care', slug: 'beauty-personal-care', description: 'Skincare, makeup, and grooming products', image: 'https://images.pexels.com/photos/3373739/pexels-photo-3373739.jpeg?auto=compress&cs=tinysrgb&w=400', icon: 'spa', parentId: undefined, productCount: 1780, isActive: true },
    { id: 'cat7', name: 'Toys & Games', slug: 'toys-games', description: 'Toys and games for all ages', image: 'https://images.pexels.com/photos/163064/play-house-toy-child-163064.jpeg?auto=compress&cs=tinysrgb&w=400', icon: 'toys', parentId: undefined, productCount: 920, isActive: true },
    { id: 'cat8', name: 'Automotive', slug: 'automotive', description: 'Car accessories and parts', image: 'https://images.pexels.com/photos/1905741/pexels-photo-1905741.jpeg?auto=compress&cs=tinysrgb&w=400', icon: 'directions_car', parentId: undefined, productCount: 450, isActive: true }
  ];

  private vendors: Vendor[] = [
    { id: 'v1', email: 'techstore@vendor.com', password: 'vendor123', firstName: 'Rajesh', lastName: 'Kumar', phone: '9876543210', role: 'vendor', storeName: 'TechStore Pro', storeDescription: 'Premium electronics and gadgets store with best deals on smartphones, laptops, and accessories.', storeLogo: 'https://images.pexels.com/photos/3945683/pexels-photo-3945683.jpeg?auto=compress&cs=tinysrgb&w=100', storeBanner: 'https://images.pexels.com/photos/3945683/pexels-photo-3945683.jpeg?auto=compress&cs=tinysrgb&w=1200', businessEmail: 'business@techstore.com', businessPhone: '9876543210', gstNumber: '29AABCT1234F1ZM', panNumber: 'AABCT1234F', bankAccountNo: '1234567890', bankIfsc: 'SBIN0001234', bankName: 'State Bank of India', rating: 4.8, totalProducts: 156, totalSales: 12500, isVerified: true, createdAt: new Date('2023-01-15') },
    { id: 'v2', email: 'fashionhub@vendor.com', password: 'vendor123', firstName: 'Priya', lastName: 'Sharma', phone: '9876543211', role: 'vendor', storeName: 'Fashion Hub', storeDescription: 'Trendy fashion store for men and women. Latest styles at affordable prices.', storeLogo: 'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=100', storeBanner: 'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=1200', businessEmail: 'biz@fashionhub.com', businessPhone: '9876543211', gstNumber: '27AABCF5678L1ZN', panNumber: 'AABCF5678L', bankAccountNo: '2345678901', bankIfsc: 'HDFC0005678', bankName: 'HDFC Bank', rating: 4.6, totalProducts: 234, totalSales: 8900, isVerified: true, createdAt: new Date('2023-02-20') },
    { id: 'v3', email: 'homespecial@vendor.com', password: 'vendor123', firstName: 'Amit', lastName: 'Patel', phone: '9876543212', role: 'vendor', storeName: 'Home Special', storeDescription: 'Quality home and kitchen products for every household need.', storeLogo: 'https://images.pexels.com/photos/1643343/pexels-photo-1643343.jpeg?auto=compress&cs=tinysrgb&w=100', storeBanner: 'https://images.pexels.com/photos/1643343/pexels-photo-1643343.jpeg?auto=compress&cs=tinysrgb&w=1200', businessEmail: 'contact@homespecial.com', businessPhone: '9876543212', gstNumber: '19AABCH9012M1ZO', panNumber: 'AABCH9012M', bankAccountNo: '3456789012', bankIfsc: 'ICICI0009012', bankName: 'ICICI Bank', rating: 4.4, totalProducts: 89, totalSales: 5600, isVerified: true, createdAt: new Date('2023-03-10') },
    { id: 'v4', email: 'sportzone@vendor.com', password: 'vendor123', firstName: 'Suresh', lastName: 'Verma', phone: '9876543213', role: 'vendor', storeName: 'Sport Zone', storeDescription: 'Premium sports equipment and fitness gear for professionals and enthusiasts.', storeLogo: 'https://images.pexels.com/photos/4162472/pexels-photo-4162472.jpeg?auto=compress&cs=tinysrgb&w=100', storeBanner: 'https://images.pexels.com/photos/4162472/pexels-photo-4162472.jpeg?auto=compress&cs=tinysrgb&w=1200', businessEmail: 'sales@sportzone.com', businessPhone: '9876543213', gstNumber: '24AABCS3456P1ZR', panNumber: 'AABCS3456P', bankAccountNo: '4567890123', bankIfsc: 'AXIS0003456', bankName: 'AXIS Bank', rating: 4.5, totalProducts: 67, totalSales: 3200, isVerified: true, createdAt: new Date('2023-04-05') },
    { id: 'v5', email: 'bookworld@vendor.com', password: 'vendor123', firstName: 'Neha', lastName: 'Gupta', phone: '9876543214', role: 'vendor', storeName: 'Book World', storeDescription: 'Your one-stop shop for books across all genres and categories.', storeLogo: 'https://images.pexels.com/photos/159711/books-bookstore-book-reading-159711.jpeg?auto=compress&cs=tinysrgb&w=100', storeBanner: 'https://images.pexels.com/photos/159711/books-bookstore-book-reading-159711.jpeg?auto=compress&cs=tinysrgb&w=1200', businessEmail: 'info@bookworld.com', businessPhone: '9876543214', gstNumber: '12AABCB7890K1ZP', panNumber: 'AABCB7890K', bankAccountNo: '5678901234', bankIfsc: 'KMBL0007890', bankName: 'Kotak Mahindra', rating: 4.7, totalProducts: 450, totalSales: 7800, isVerified: true, createdAt: new Date('2023-05-15') }
  ];

  private products: Product[] = [
    { id: 'p1', vendorId: 'v1', categoryId: 'cat1', name: 'iPhone 15 Pro Max', slug: 'iphone-15-pro-max', description: 'The most powerful iPhone ever with A17 Pro chip, 5x optical zoom camera system, and titanium design. Features include Dynamic Island, always-on display, and up to 29 hours video playback.', shortDescription: 'Most powerful iPhone with A17 Pro chip and titanium design', images: [{ id: 'img1', url: 'https://images.pexels.com/photos/7889460/pexels-photo-7889460.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'iPhone 15 Pro Max', isPrimary: true }], variants: [{ id: 'v1-1', name: '128GB Natural Titanium', sku: 'IPHONE15PM-128-NT', price: 134900, comparePrice: 149900, stock: 45, image: undefined, attributes: { 'Storage': '128GB', 'Color': 'Natural Titanium' } }, { id: 'v1-2', name: '256GB Blue Titanium', sku: 'IPHONE15PM-256-BT', price: 154900, comparePrice: 169900, stock: 32, image: undefined, attributes: { 'Storage': '256GB', 'Color': 'Blue Titanium' } }], specifications: { 'Display': '6.7" Super Retina XDR', 'Processor': 'A17 Pro chip', 'Camera': '48MP Main, 12MP Ultra Wide, 12MP Telephoto', 'Battery': 'Up to 29 hours video playback', 'OS': 'iOS 17' }, tags: ['apple', 'iPhone', 'smartphone', 'premium'], rating: 4.8, totalReviews: 234, status: 'approved', isFeatured: true, isTrending: true, createdAt: new Date('2024-01-15'), updatedAt: new Date('2024-06-01') },
    { id: 'p2', vendorId: 'v1', categoryId: 'cat1', name: 'Samsung Galaxy S24 Ultra', slug: 'samsung-galaxy-s24-ultra', description: 'Galaxy AI is here. The ultimate Galaxy with AI ready features, 200MP camera with 100x Space Zoom, and S Pen included.', shortDescription: 'Galaxy AI with 200MP camera and S Pen', images: [{ id: 'img2', url: 'https://images.pexels.com/photos/607835/pexels-photo-607835.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Samsung Galaxy S24 Ultra', isPrimary: true }], variants: [{ id: 'v2-1', name: '256GB Titanium Black', sku: 'S24U-256-TB', price: 129999, comparePrice: 139999, stock: 56, image: undefined, attributes: { 'Storage': '256GB', 'Color': 'Titanium Black' } }, { id: 'v2-2', name: '512GB Titanium Gray', sku: 'S24U-512-TG', price: 149999, comparePrice: 159999, stock: 28, image: undefined, attributes: { 'Storage': '512GB', 'Color': 'Titanium Gray' } }], specifications: { 'Display': '6.8" Dynamic AMOLED 2X', 'Processor': 'Snapdragon 8 Gen 3', 'Camera': '200MP Main, 12MP Ultra Wide, 50MP Telephoto', 'Battery': '5000mAh', 'OS': 'Android 14, One UI 6.1' }, tags: ['samsung', 'galaxy', 'smartphone', 'android'], rating: 4.7, totalReviews: 189, status: 'approved', isFeatured: true, isTrending: true, createdAt: new Date('2024-02-01'), updatedAt: new Date('2024-06-01') },
    { id: 'p3', vendorId: 'v1', categoryId: 'cat1', name: 'MacBook Pro 16" M3 Max', slug: 'macbook-pro-16-m3-max', description: 'Supercharged by M3 Max. The most powerful MacBook Pro ever with up to 400GB/s memory bandwidth and up to 22 hours battery life.', shortDescription: 'Most powerful MacBook Pro with M3 Max chip', images: [{ id: 'img3', url: 'https://images.pexels.com/photos/18105315/pexels-photo-18105315.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'MacBook Pro 16', isPrimary: true }], variants: [{ id: 'v3-1', name: '36GB RAM 1TB SSD Space Black', sku: 'MBP16-M3MAX-36-1-SB', price: 249900, comparePrice: 269900, stock: 15, image: undefined, attributes: { 'RAM': '36GB', 'Storage': '1TB SSD', 'Color': 'Space Black' } }], specifications: { 'Display': '16.2" Liquid Retina XDR', 'Processor': 'Apple M3 Max', 'RAM': '36GB Unified Memory', 'Storage': '1TB SSD', 'Battery': 'Up to 22 hours' }, tags: ['apple', 'macbook', 'laptop', 'premium'], rating: 4.9, totalReviews: 156, status: 'approved', isFeatured: true, isTrending: false, createdAt: new Date('2024-03-01'), updatedAt: new Date('2024-06-01') },
    { id: 'p4', vendorId: 'v2', categoryId: 'cat2', name: 'Premium Cotton T-Shirt Set', slug: 'premium-cotton-tshirt-set', description: 'Pack of 3 premium cotton t-shirts in classic colors. Made from 100% organic cotton for maximum comfort and style.', shortDescription: 'Pack of 3 premium organic cotton t-shirts', images: [{ id: 'img4', url: 'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Cotton T-Shirt Set', isPrimary: true }], variants: [{ id: 'v4-1', name: 'Small - Navy, White, Gray', sku: 'TSHIRT-S-NWG', price: 1499, comparePrice: 1999, stock: 120, image: undefined, attributes: { 'Size': 'S', 'Colors': 'Navy, White, Gray' } }, { id: 'v4-2', name: 'Medium - Black, White, Navy', sku: 'TSHIRT-M-BWN', price: 1499, comparePrice: 1999, stock: 85, image: undefined, attributes: { 'Size': 'M', 'Colors': 'Black, White, Navy' } }, { id: 'v4-3', name: 'Large - Navy, Gray, White', sku: 'TSHIRT-L-NGW', price: 1499, comparePrice: 1999, stock: 95, image: undefined, attributes: { 'Size': 'L', 'Colors': 'Navy, Gray, White' } }], specifications: { 'Material': '100% Organic Cotton', 'Fit': 'Regular Fit', 'Care': 'Machine Washable', 'Pack Size': '3 T-shirts' }, tags: ['fashion', 'tshirt', 'cotton', 'men'], rating: 4.5, totalReviews: 312, status: 'approved', isFeatured: false, isTrending: true, createdAt: new Date('2024-01-20'), updatedAt: new Date('2024-05-15') },
    { id: 'p5', vendorId: 'v2', categoryId: 'cat2', name: 'Women\'s Designer Kurti Collection', slug: 'womens-designer-kurti-collection', description: 'Beautiful designer kurtis with intricate embroidery work. Perfect for festive occasions and daily wear.', shortDescription: 'Designer kurtis with embroidery work', images: [{ id: 'img5', url: 'https://images.pexels.com/photos/1040953/pexels-photo-1040953.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Designer Kurti', isPrimary: true }], variants: [{ id: 'v5-1', name: 'S - Red Embroidered', sku: 'KURTI-S-RED', price: 1299, comparePrice: 1799, stock: 45, image: undefined, attributes: { 'Size': 'S', 'Color': 'Red' } }, { id: 'v5-2', name: 'M - Blue Embroidered', sku: 'KURTI-M-BLUE', price: 1299, comparePrice: 1799, stock: 60, image: undefined, attributes: { 'Size': 'M', 'Color': 'Blue' } }, { id: 'v5-3', name: 'L - Green Embroidered', sku: 'KURTI-L-GREEN', price: 1299, comparePrice: 1799, stock: 38, image: undefined, attributes: { 'Size': 'L', 'Color': 'Green' } }], specifications: { 'Material': 'Cotton Blend', 'Pattern': 'Embroidered', 'Length': 'Calf Length', 'Sleeve': '3/4 Sleeve' }, tags: ['fashion', 'kurti', 'women', 'ethnic'], rating: 4.6, totalReviews: 278, status: 'approved', isFeatured: true, isTrending: false, createdAt: new Date('2024-02-15'), updatedAt: new Date('2024-05-20') },
    { id: 'p6', vendorId: 'v3', categoryId: 'cat3', name: 'Stainless Steel Cookware Set', slug: 'stainless-steel-cookware-set', description: 'Premium 10-piece stainless steel cookware set with non-stick coating. Perfect for healthy cooking.', shortDescription: '10-piece premium stainless steel cookware', images: [{ id: 'img6', url: 'https://images.pexels.com/photos/4227613/pexels-photo-4227613.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Cookware Set', isPrimary: true }], variants: [{ id: 'v6-1', name: 'Standard Set', sku: 'COOK-STD-10', price: 4999, comparePrice: 6999, stock: 67, image: undefined, attributes: { 'Pieces': '10', 'Material': 'Stainless Steel' } }], specifications: { 'Material': 'Food Grade Stainless Steel', 'Coating': 'Non-stick', 'Pieces': '10', 'Induction Ready': 'Yes', 'Dishwasher Safe': 'Yes' }, tags: ['kitchen', 'cookware', 'home', 'stainless'], rating: 4.4, totalReviews: 145, status: 'approved', isFeatured: false, isTrending: false, createdAt: new Date('2024-03-10'), updatedAt: new Date('2024-05-25') },
    { id: 'p7', vendorId: 'v3', categoryId: 'cat3', name: 'Ergonomic Office Chair', slug: 'ergonomic-office-chair', description: 'Premium ergonomic office chair with lumbar support, adjustable armrests, and breathable mesh back.', shortDescription: 'Ergonomic chair with lumbar support', images: [{ id: 'img7', url: 'https://images.pexels.com/photos/1595385/pexels-photo-1595385.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Office Chair', isPrimary: true }], variants: [{ id: 'v7-1', name: 'Black Mesh', sku: 'CHAIR-BLK-MESH', price: 7999, comparePrice: 9999, stock: 34, image: undefined, attributes: { 'Color': 'Black', 'Type': 'Mesh Back' } }, { id: 'v7-2', name: 'Gray Mesh', sku: 'CHAIR-GRAY-MESH', price: 7999, comparePrice: 9999, stock: 28, image: undefined, attributes: { 'Color': 'Gray', 'Type': 'Mesh Back' } }], specifications: { 'Material': 'Breathable Mesh', 'Adjustability': 'Height, Armrest, Tilt', 'Weight Capacity': '150kg', 'Warranty': '3 Years' }, tags: ['furniture', 'office', 'chair', 'ergonomic'], rating: 4.3, totalReviews: 89, status: 'approved', isFeatured: false, isTrending: true, createdAt: new Date('2024-04-01'), updatedAt: new Date('2024-06-01') },
    { id: 'p8', vendorId: 'v4', categoryId: 'cat4', name: 'Professional Yoga Mat', slug: 'professional-yoga-mat', description: 'Premium non-slip yoga mat with extra thickness for comfort. Perfect for yoga, pilates, and fitness exercises.', shortDescription: 'Premium non-slip thick yoga mat', images: [{ id: 'img8', url: 'https://images.pexels.com/photos/4662438/pexels-photo-4662438.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Yoga Mat', isPrimary: true }], variants: [{ id: 'v8-1', name: 'Purple - 6mm', sku: 'YM-PUR-6MM', price: 999, comparePrice: 1499, stock: 150, image: undefined, attributes: { 'Color': 'Purple', 'Thickness': '6mm' } }, { id: 'v8-2', name: 'Blue - 8mm', sku: 'YM-BLU-8MM', price: 1199, comparePrice: 1699, stock: 95, image: undefined, attributes: { 'Color': 'Blue', 'Thickness': '8mm' } }, { id: 'v8-3', name: 'Green - 6mm', sku: 'YM-GRN-6MM', price: 999, comparePrice: 1499, stock: 120, image: undefined, attributes: { 'Color': 'Green', 'Thickness': '6mm' } }], specifications: { 'Material': 'Eco-Friendly TPE', 'Thickness': '6mm/8mm', 'Dimensions': '72" x 24"', 'Non-Slip': 'Yes' }, tags: ['yoga', 'fitness', 'sports', 'mat'], rating: 4.7, totalReviews: 234, status: 'approved', isFeatured: false, isTrending: false, createdAt: new Date('2024-01-25'), updatedAt: new Date('2024-05-10') },
    { id: 'p9', vendorId: 'v4', categoryId: 'cat4', name: 'Adjustable Dumbbell Set', slug: 'adjustable-dumbbell-set', description: 'Space-saving adjustable dumbbell set. Weight range from 2.5kg to 25kg per dumbbell with quick adjustment mechanism.', shortDescription: 'Adjustable dumbbells 2.5kg-25kg', images: [{ id: 'img9', url: 'https://images.pexels.com/photos/4162472/pexels-photo-4162472.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Dumbbell Set', isPrimary: true }], variants: [{ id: 'v9-1', name: 'Single Dumbbell', sku: 'DB-SINGLE-ADJ', price: 8999, comparePrice: 11999, stock: 45, image: undefined, attributes: { 'Type': 'Single', 'Max Weight': '25kg' } }, { id: 'v9-2', name: 'Pair', sku: 'DB-PAIR-ADJ', price: 15999, comparePrice: 19999, stock: 32, image: undefined, attributes: { 'Type': 'Pair', 'Max Weight': '25kg each' } }], specifications: { 'Weight Range': '2.5kg - 25kg', 'Increment': '2.5kg', 'Material': 'Steel with Rubber Grip', 'Warranty': '2 Years' }, tags: ['fitness', 'gym', 'weights', 'dumbbells'], rating: 4.6, totalReviews: 167, status: 'approved', isFeatured: true, isTrending: false, createdAt: new Date('2024-02-28'), updatedAt: new Date('2024-05-15') },
    { id: 'p10', vendorId: 'v5', categoryId: 'cat5', name: 'Bestseller Book Bundle', slug: 'bestseller-book-bundle', description: 'Collection of 5 bestselling novels across different genres. Perfect gift for book lovers.', shortDescription: '5 bestselling novels bundle', images: [{ id: 'img10', url: 'https://images.pexels.com/photos/159711/books-bookstore-book-reading-159711.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Book Bundle', isPrimary: true }], variants: [{ id: 'v10-1', name: 'Fiction Bundle', sku: 'BOOK-FIC-BUNDLE', price: 999, comparePrice: 1499, stock: 200, image: undefined, attributes: { 'Genre': 'Fiction', 'Books': '5' } }, { id: 'v10-2', name: 'Self-Help Bundle', sku: 'BOOK-SELF-BUNDLE', price: 1199, comparePrice: 1699, stock: 170, image: undefined, attributes: { 'Genre': 'Self-Help', 'Books': '5' } }, { id: 'v10-3', name: 'Business Bundle', sku: 'BOOK-BIZ-BUNDLE', price: 1399, comparePrice: 1899, stock: 145, image: undefined, attributes: { 'Genre': 'Business', 'Books': '5' } }], specifications: { 'Format': 'Paperback', 'Language': 'English', 'Pages': 'Varies', 'Publisher': 'Multiple Publishers' }, tags: ['books', 'reading', 'fiction', 'bestseller'], rating: 4.5, totalReviews: 189, status: 'approved', isFeatured: false, isTrending: false, createdAt: new Date('2024-03-15'), updatedAt: new Date('2024-05-20') },
    { id: 'p11', vendorId: 'v1', categoryId: 'cat1', name: 'Sony WH-1000XM5 Headphones', slug: 'sony-wh-1000xm5-headphones', description: 'Industry-leading noise cancellation with exceptional sound quality. 30-hour battery life with quick charging.', shortDescription: 'Premium noise cancelling headphones', images: [{ id: 'img11', url: 'https://images.pexels.com/photos/3945683/pexels-photo-3945683.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Sony Headphones', isPrimary: true }], variants: [{ id: 'v11-1', name: 'Black', sku: 'SONY-XM5-BLK', price: 29990, comparePrice: 34990, stock: 55, image: undefined, attributes: { 'Color': 'Black' } }, { id: 'v11-2', name: 'Silver', sku: 'SONY-XM5-SLV', price: 29990, comparePrice: 34990, stock: 40, image: undefined, attributes: { 'Color': 'Silver' } }], specifications: { 'Type': 'Over-Ear', 'Noise Cancellation': 'Active', 'Battery': '30 hours', 'Driver': '30mm', 'Bluetooth': '5.2' }, tags: ['headphones', 'audio', 'sony', 'premium'], rating: 4.8, totalReviews: 267, status: 'approved', isFeatured: true, isTrending: true, createdAt: new Date('2024-04-10'), updatedAt: new Date('2024-06-01') },
    { id: 'p12', vendorId: 'v2', categoryId: 'cat6', name: 'Premium Skincare Gift Set', slug: 'premium-skincare-gift-set', description: 'Complete skincare routine set with cleanser, toner, serum, moisturizer, and sunscreen. Suitable for all skin types.', shortDescription: 'Complete 5-piece skincare routine', images: [{ id: 'img12', url: 'https://images.pexels.com/photos/3373739/pexels-photo-3373739.jpeg?auto=compress&cs=tinysrgb&w=600', alt: 'Skincare Set', isPrimary: true }], variants: [{ id: 'v12-1', name: 'Normal/Dry Skin', sku: 'SKIN-DRY-SET', price: 2499, comparePrice: 3499, stock: 80, image: undefined, attributes: { 'Skin Type': 'Normal/Dry', 'Pieces': '5' } }, { id: 'v12-2', name: 'Oily/Combination Skin', sku: 'SKIN-OILY-SET', price: 2499, comparePrice: 3499, stock: 95, image: undefined, attributes: { 'Skin Type': 'Oily/Combination', 'Pieces': '5' } }], specifications: { 'Contents': 'Cleanser, Toner, Serum, Moisturizer, Sunscreen', 'Type': 'Paraben-Free', 'Size': '50ml each', 'Suitable For': 'All Skin Types' }, tags: ['beauty', 'skincare', 'gift', 'premium'], rating: 4.4, totalReviews: 156, status: 'approved', isFeatured: false, isTrending: true, createdAt: new Date('2024-05-01'), updatedAt: new Date('2024-06-01') }
  ];

  private banners: Banner[] = [
    { id: 'b1', title: 'Mega Sale Week', subtitle: 'Up to 70% off on Electronics', image: 'https://images.pexels.com/photos/3945683/pexels-photo-3945683.jpeg?auto=compress&cs=tinysrgb&w=1200', link: '/products?category=electronics', buttonText: 'Shop Now', position: 'home_hero', isActive: true, sortOrder: 1, startDate: new Date('2024-01-01'), endDate: new Date('2024-12-31') },
    { id: 'b2', title: 'Fashion Fest', subtitle: 'Latest trends at amazing prices', image: 'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=1200', link: '/products?category=fashion', buttonText: 'Explore', position: 'home_hero', isActive: true, sortOrder: 2, startDate: new Date('2024-01-01'), endDate: new Date('2024-12-31') },
    { id: 'b3', title: 'New Arrivals', subtitle: 'Check out the latest products', image: 'https://images.pexels.com/photos/4162472/pexels-photo-4162472.jpeg?auto=compress&cs=tinysrgb&w=800', link: '/products', buttonText: 'View All', position: 'home_promo', isActive: true, sortOrder: 1, startDate: new Date('2024-01-01'), endDate: new Date('2024-12-31') }
  ];

  private coupons: Coupon[] = [
    { id: 'c1', code: 'WELCOME10', type: 'percentage', value: 10, minOrderAmount: 500, maxDiscount: 200, usageLimit: 10000, usedCount: 4567, validFrom: new Date('2024-01-01'), validUntil: new Date('2024-12-31'), isActive: true },
    { id: 'c2', code: 'FLAT200', type: 'fixed', value: 200, minOrderAmount: 1500, maxDiscount: 200, usageLimit: 5000, usedCount: 2345, validFrom: new Date('2024-01-01'), validUntil: new Date('2024-12-31'), isActive: true },
    { id: 'c3', code: 'MEGA20', type: 'percentage', value: 20, minOrderAmount: 2500, maxDiscount: 500, usageLimit: 1000, usedCount: 456, validFrom: new Date('2024-06-01'), validUntil: new Date('2024-06-30'), isActive: true }
  ];

  private customers: Customer[] = [
    { id: 'cust1', email: 'john.doe@email.com', password: 'password123', firstName: 'John', lastName: 'Doe', phone: '9876543215', role: 'customer', addresses: [{ id: 'addr1', type: 'home', fullName: 'John Doe', phone: '9876543215', addressLine1: '123 Main Street', addressLine2: 'Apt 4B', city: 'Mumbai', state: 'Maharashtra', pincode: '400001', isDefault: true }], wishlist: ['p1', 'p3', 'p8'], cartItems: [{ productId: 'p1', variantId: 'v1-1', quantity: 1 }, { productId: 'p4', variantId: 'v4-2', quantity: 2 }], createdAt: new Date('2024-01-15') },
    { id: 'cust2', email: 'jane.smith@email.com', password: 'password123', firstName: 'Jane', lastName: 'Smith', phone: '9876543216', role: 'customer', addresses: [{ id: 'addr2', type: 'work', fullName: 'Jane Smith', phone: '9876543216', addressLine1: '456 Park Avenue', city: 'Delhi', state: 'Delhi', pincode: '110001', isDefault: true }], wishlist: ['p2', 'p5'], cartItems: [{ productId: 'p5', variantId: 'v5-2', quantity: 1 }], createdAt: new Date('2024-02-20') }
  ];

  private admins: Admin[] = [
    { id: 'admin1', email: 'admin@marketplace.com', password: 'admin123', firstName: 'Admin', lastName: 'User', phone: '9876543200', role: 'admin', permissions: ['all'], createdAt: new Date('2023-01-01') }
  ];

  private orders: Order[] = [
    { id: 'ord1', orderNumber: 'ORD-2024-00001', customerId: 'cust1', customerName: 'John Doe', customerEmail: 'john.doe@email.com', items: [{ productId: 'p2', productName: 'Samsung Galaxy S24 Ultra', productImage: 'https://images.pexels.com/photos/607835/pexels-photo-607835.jpeg?auto=compress&cs=tinysrgb&w=100', variantId: 'v2-1', variantName: '256GB Titanium Black', quantity: 1, price: 129999, total: 129999, vendorId: 'v1', vendorName: 'TechStore Pro' }], subtotal: 129999, discount: 13000, couponCode: 'MEGA20', shippingCost: 0, tax: 23400, total: 140399, shippingAddress: { fullName: 'John Doe', phone: '9876543215', addressLine1: '123 Main Street', addressLine2: 'Apt 4B', city: 'Mumbai', state: 'Maharashtra', pincode: '400001' }, payment: { method: 'card', status: 'completed', transactionId: 'TXN123456', paidAt: new Date('2024-05-15') }, status: 'delivered', tracking: [{ status: 'confirmed', timestamp: new Date('2024-05-15'), description: 'Order confirmed' }, { status: 'shipped', timestamp: new Date('2024-05-16'), description: 'Shipped from warehouse', location: 'Mumbai' }, { status: 'delivered', timestamp: new Date('2024-05-18'), description: 'Delivered successfully' }], estimatedDelivery: new Date('2024-05-20'), deliveredAt: new Date('2024-05-18'), createdAt: new Date('2024-05-15'), updatedAt: new Date('2024-05-18') },
    { id: 'ord2', orderNumber: 'ORD-2024-00002', customerId: 'cust1', customerName: 'John Doe', customerEmail: 'john.doe@email.com', items: [{ productId: 'p4', productName: 'Premium Cotton T-Shirt Set', productImage: 'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=100', variantId: 'v4-2', variantName: 'Medium - Black, White, Navy', quantity: 2, price: 1499, total: 2998, vendorId: 'v2', vendorName: 'Fashion Hub' }], subtotal: 2998, discount: 0, shippingCost: 49, tax: 540, total: 3587, shippingAddress: { fullName: 'John Doe', phone: '9876543215', addressLine1: '123 Main Street', addressLine2: 'Apt 4B', city: 'Mumbai', state: 'Maharashtra', pincode: '400001' }, payment: { method: 'cod', status: 'pending' }, status: 'shipped', tracking: [{ status: 'confirmed', timestamp: new Date('2024-06-01'), description: 'Order confirmed' }, { status: 'shipped', timestamp: new Date('2024-06-02'), description: 'Shipped from warehouse', location: 'Delhi' }], estimatedDelivery: new Date('2024-06-08'), createdAt: new Date('2024-06-01'), updatedAt: new Date('2024-06-02') },
    { id: 'ord3', orderNumber: 'ORD-2024-00003', customerId: 'cust2', customerName: 'Jane Smith', customerEmail: 'jane.smith@email.com', items: [{ productId: 'p5', productName: "Women's Designer Kurti Collection", productImage: 'https://images.pexels.com/photos/1040953/pexels-photo-1040953.jpeg?auto=compress&cs=tinysrgb&w=100', variantId: 'v5-2', variantName: 'M - Blue Embroidered', quantity: 2, price: 1299, total: 2598, vendorId: 'v2', vendorName: 'Fashion Hub' }], subtotal: 2598, discount: 260, couponCode: 'WELCOME10', shippingCost: 0, tax: 421, total: 2759, shippingAddress: { fullName: 'Jane Smith', phone: '9876543216', addressLine1: '456 Park Avenue', city: 'Delhi', state: 'Delhi', pincode: '110001' }, payment: { method: 'upi', status: 'completed', transactionId: 'UPI987654', paidAt: new Date('2024-06-05') }, status: 'processing', tracking: [{ status: 'confirmed', timestamp: new Date('2024-06-05'), description: 'Order confirmed' }], estimatedDelivery: new Date('2024-06-12'), createdAt: new Date('2024-06-05'), updatedAt: new Date('2024-06-05') }
  ];

  private reviews: ProductReview[] = [
    { id: 'rev1', productId: 'p1', customerId: 'cust1', customerName: 'John Doe', rating: 5, title: 'Amazing phone!', comment: 'Best iPhone I have ever used. The camera quality is exceptional and the battery lasts all day.', isVerifiedPurchase: true, helpfulCount: 45, createdAt: new Date('2024-04-20') },
    { id: 'rev2', productId: 'p2', customerId: 'cust2', customerName: 'Jane Smith', rating: 4, title: 'Great Android flagship', comment: 'Love the S Pen features and camera zoom. Minor UI bugs but overall excellent.', isVerifiedPurchase: true, helpfulCount: 32, createdAt: new Date('2024-05-10') }
  ];

  private returnRequests: ReturnRequest[] = [];

  private supportTickets: SupportTicket[] = [];

  constructor() {}

  getCategories(): Category[] { return this.categories; }
  getCategoryBySlug(slug: string): Category | undefined { return this.categories.find(c => c.slug === slug); }
  getCategoryById(id: string): Category | undefined { return this.categories.find(c => c.id === id); }

  getVendors(): Vendor[] { return this.vendors; }
  getVendorById(id: string): Vendor | undefined { return this.vendors.find(v => v.id === id); }

  getProducts(): Product[] { return this.products; }
  getProductById(id: string): Product | undefined { return this.products.find(p => p.id === id); }
  getProductsByCategory(categoryId: string): Product[] { return this.products.filter(p => p.categoryId === categoryId); }
  getProductsByVendor(vendorId: string): Product[] { return this.products.filter(p => p.vendorId === vendorId); }
  getFeaturedProducts(): Product[] { return this.products.filter(p => p.isFeatured); }
  getTrendingProducts(): Product[] { return this.products.filter(p => p.isTrending); }
  searchProducts(query: string): Product[] { return this.products.filter(p => p.name.toLowerCase().includes(query.toLowerCase()) || p.tags.some(t => t.toLowerCase().includes(query.toLowerCase()))); }

  getBanners(): Banner[] { return this.banners.filter(b => b.isActive); }

  getCoupons(): Coupon[] { return this.coupons; }
  validateCoupon(code: string): Coupon | undefined { return this.coupons.find(c => c.code === code && c.isActive && new Date() >= c.validFrom && new Date() <= c.validUntil); }

  getCustomers(): Customer[] { return this.customers; }
  getCustomerById(id: string): Customer | undefined { return this.customers.find(c => c.id === id); }

  getAdmins(): Admin[] { return this.admins; }
  getAdminById(id: string): Admin | undefined { return this.admins.find(a => a.id === id); }

  getOrders(): Order[] { return this.orders; }
  getOrderById(id: string): Order | undefined { return this.orders.find(o => o.id === id); }
  getOrdersByCustomer(customerId: string): Order[] { return this.orders.filter(o => o.customerId === customerId); }
  getOrdersByVendor(vendorId: string): Order[] { return this.orders.filter(o => o.items.some(i => i.vendorId === vendorId)); }

  getReviews(): ProductReview[] { return this.reviews; }
  getReviewsForProduct(productId: string): ProductReview[] { return this.reviews.filter(r => r.productId === productId); }

  getReturnRequests(): ReturnRequest[] { return this.returnRequests; }
  getSupportTickets(): SupportTicket[] { return this.supportTickets; }
}
